// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmR_q9w1OotnK8a95D-h0loR_m1eoBkTw',
    appId: '1:590142168662:web:e610d2c88ec2e93a5ee5f7',
    messagingSenderId: '590142168662',
    projectId: 'vs6451071051',
    authDomain: 'vs6451071051.firebaseapp.com',
    storageBucket: 'vs6451071051.firebasestorage.app',
    measurementId: 'G-X2KREKBLDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKICJsTgFhXYyrEXH3zqghmW0UFctqXY',
    appId: '1:590142168662:android:7fa2ff39446292d55ee5f7',
    messagingSenderId: '590142168662',
    projectId: 'vs6451071051',
    storageBucket: 'vs6451071051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHu6ksphGYNzgmbK7nmZONZRNS8piFEJA',
    appId: '1:590142168662:ios:161a93ffffd0574c5ee5f7',
    messagingSenderId: '590142168662',
    projectId: 'vs6451071051',
    storageBucket: 'vs6451071051.firebasestorage.app',
    iosBundleId: 'com.example.btl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHu6ksphGYNzgmbK7nmZONZRNS8piFEJA',
    appId: '1:590142168662:ios:161a93ffffd0574c5ee5f7',
    messagingSenderId: '590142168662',
    projectId: 'vs6451071051',
    storageBucket: 'vs6451071051.firebasestorage.app',
    iosBundleId: 'com.example.btl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmR_q9w1OotnK8a95D-h0loR_m1eoBkTw',
    appId: '1:590142168662:web:44e63b9394418be05ee5f7',
    messagingSenderId: '590142168662',
    projectId: 'vs6451071051',
    authDomain: 'vs6451071051.firebaseapp.com',
    storageBucket: 'vs6451071051.firebasestorage.app',
    measurementId: 'G-JKX71R6KX2',
  );
}
